use_frameworks!

platform :ios, '11.0'

target 'ZKSyncExample' do
  pod 'ZKSync', :path => '../../'
  
  target 'ZKSyncExampleTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
        end
    end
end
 
